using CodingTrackerLibrary.Models;
using Microsoft.Data.Sqlite;
using Dapper;

namespace CodingTrackerLibrary.Controllers.Database;
internal class DatabaseManager
{
    private readonly string? connectionString;
    public DatabaseManager(bool dummyData = false)
    {
        int queryLength = 0;
        this.connectionString = Utilities.GetConnectionString();
        using var connection = new SqliteConnection(this.connectionString);
        connection.Open();

        var tableCommand = connection.CreateCommand();
        tableCommand.CommandText =
            @"CREATE TABLE IF NOT EXISTS CodingTracker (
                        Id INTEGER PRIMARY KEY AUTOINCREMENT,
                        StartDate TEXT,
                        EndDate TEXT,
                        Duration FLOAT,
                        Units TEXT DEFAULT 'hours'
                    )";
        tableCommand.ExecuteNonQuery();

        tableCommand.CommandText = "SELECT COUNT(*) FROM CodingTracker";
        queryLength = Convert.ToInt32(tableCommand.ExecuteScalar());

        connection.Close();

        if (dummyData || queryLength == 0) this.AutoGenerateData();
    }

    private void AutoGenerateData()
    {
        var dummyCodingHabits = new List<CodingSession>
        {
            new ( startDate:  "2020-01-16", endDate: "2020-01-17", duration: 24),
            new ( startDate:  "2020-01-18", endDate: "2020-01-20", duration: 48),
            new ( startDate:  "2020-01-21", endDate: "2020-01-24", duration: 72),
            new ( startDate:  "2020-01-25", endDate: "2020-01-29", duration: 96),
            new ( startDate:  "2021-01-13", endDate: "2021-01-18", duration: 120)
        };

        using var connection = new SqliteConnection(this.connectionString);
        connection.Open();

        var sql = "INSERT INTO CodingTracker (StartDate, EndDate, Duration) VALUES (@StartDate, @EndDate, @Duration)";
        
        connection.Execute(sql, dummyCodingHabits);

        connection.Close();
    }

    public CodingSession Get(int id)
    {
        using var connection = new SqliteConnection(this.connectionString);
        connection.Open();

        string sql = "SELECT * FROM CodingTracker WHERE Id=@Id";
        CodingSession session = connection.QuerySingle<CodingSession>(sql, new CodingSession(id));

        connection.Close();

        return session;
    }

    public List<CodingSession> GetAllData()
    {
        List<CodingSession> codingSessions = new();
        using var connection = new SqliteConnection(this.connectionString);
        connection.Open();

        codingSessions = connection.Query<CodingSession>("SELECT * FROM CodingTracker").ToList();

        connection.Close();
        return codingSessions;
    }

    public int GetNumberOfEntries()
    {
        int queryLength;
        using var connection = new SqliteConnection(this.connectionString);
        
        connection.Open();
        
        var sql = "SELECT COUNT(*) FROM CodingTracker";
        queryLength = connection.QuerySingle<int>(sql);
        
        connection.Close();

        return queryLength;
    }

    public bool IDExists(int id)
    {
        int queryLength;
        using var connection = new SqliteConnection(this.connectionString);

        connection.Open();

        var sql = "SELECT COUNT(*) FROM CodingTracker WHERE Id=@Id";
        CodingSession cs = new CodingSession(id);

        queryLength = connection.ExecuteScalar<int>(sql, cs);

        connection.Close();

        return queryLength > 0;
    }

    public void Update(ref int ID, ref DateTime startDate, ref DateTime endDate, TimeSpan duration)
    {
        using var connection = new SqliteConnection(this.connectionString);
        connection.Open();
        var sql = @"UPDATE CodingTracker
                      SET StartDate = @StartDate,
                          EndDate = @EndDate,
                          Duration = @Duration
                      WHERE
                          Id = @Id";

        CodingSession cs = 
            new CodingSession(ID, 
                              startDate.ToString("yyyy-MM-dd"), 
                              endDate.ToString("yyyy-MM-dd"), 
                              (float)duration.TotalHours);
        
        connection.Execute(sql, cs);   
        connection.Close();
    }

    public void Delete(ref int id)
    {
        using var connection = new SqliteConnection(this.connectionString);
        connection.Open();

        var sql = "DELETE FROM CodingTracker WHERE Id=@Id";
        CodingSession cs = new(id);

        connection.Execute(sql, cs);

        connection.Close();
    }

    public void ClearDatabase()
    {
        using var connection = new SqliteConnection(this.connectionString);
        connection.Open();

        string sql = "DELETE FROM CodingTracker";
        connection.Execute(sql);

        sql = "UPDATE sqlite_sequence SET seq = 0 WHERE name = 'CodingTracker'";
        connection.Execute(sql);

        connection.Close();
    }

    public void Insert(ref DateTime startDate, ref DateTime endDate, TimeSpan duration)
    {
        using var connection = new SqliteConnection(this.connectionString);
        connection.Open();
        
        var sql = @"INSERT INTO CodingTracker (StartDate, EndDate, Duration)
                       VALUES(@StartDate, @EndDate, @Duration)";

        CodingSession cs = 
            new CodingSession(startDate.ToString("yyyy-MM-dd"), 
                              endDate.ToString("yyyy-MM-dd"), 
                              (float)duration.TotalHours);
        
        connection.Execute(sql, cs);
        
        connection.Close();
    }

    public List<CodingSession> GetDataFromDate(ref DateTime start, ref DateTime end)
    {
        List<CodingSession> codingSessions = new List<CodingSession>();
        using var connection = new SqliteConnection(this.connectionString);
        
        connection.Open();
        
        CodingSession finder = new(start.ToString("yyyy-MM-dd"), end.ToString("yyyy-MM-dd"), 0);
        codingSessions = connection.Query<CodingSession>(@"SELECT * FROM CodingTracker 
            WHERE DATE(StartDate) BETWEEN DATE(@StartDate) AND DATE(@EndDate)", finder).ToList();

        connection.Close();
        
        return codingSessions;
    }

    public int GetTotalQuantity()
    {
        int total = 0; 
        using var connection = new SqliteConnection(this.connectionString);
        connection.Open();

        total = connection.ExecuteScalar<int>("SELECT SUM(Duration) FROM CodingTracker");

        connection.Close();
        return total; 
    }

    public int GetTotalQuantityFromMonth(ref int month)
    {
        int total = 0;
        using var connection = new SqliteConnection(this.connectionString);
        connection.Open();

        var sql = @"SELECT SUM(Duration) 
                FROM CodingTracker
                WHERE strftime('%m', StartDate) = strftime('%m', @StartDate)";

        CodingSession cs = new(new DateTime(0001, month, 1).ToString("yyyy-MM-dd"));
        total = connection.ExecuteScalar<int>(sql, cs);

        connection.Close();
        return total;
    }

    public List<CodingSession> GetDataSortedBy(SortingSelections sortBy, Period period)
    {
        List<CodingSession> codingSessions = new List<CodingSession>();

        using var connection = new SqliteConnection(this.connectionString);
        connection.Open();

        var sql = @$"SELECT *
                    FROM CodingTracker
                    ORDER BY Duration {sortBy}";

        using var reader = connection.ExecuteReader(sql);
        while (reader.Read())
            codingSessions.Add(new CodingSession(reader.GetInt32(0),
                                                 reader.GetString(1),
                                                 reader.GetString(2),
                                                 reader.GetFloat(3) / (int)period,
                                                 period.ToString()));

        connection.Close();
        return codingSessions;
    }

    public int GetHoursUntilGoal(ref DateTime startingTime)
    {
        int totalDuration = 0;
        using var connection = new SqliteConnection(this.connectionString);
        connection.Open();

        var sql = @$"SELECT SUM(duration) FROM CodingTracker WHERE DATE(StartDate) = @StartDate";
        CodingSession cs = new CodingSession(startDate: startingTime.ToString("yyyy-MM-dd"));

        totalDuration = connection.ExecuteScalar<int>(sql, cs);
        connection.Close();

        return totalDuration;
    }
}

